# Generated by Django 5.0.7 on 2024-07-29 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='frequency',
            field=models.CharField(choices=[('a', 'As they are published(maximum twice a week)'), ('w', 'Once a week'), ('m', 'Once a month')], default='w', max_length=1),
        ),
    ]
