# Generated by Django 5.0.7 on 2024-09-10 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_blog_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='token',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
