# Generated by Django 5.0.7 on 2024-09-10 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_subscription_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='token',
            field=models.CharField(default='', max_length=256),
        ),
    ]
