# Generated by Django 5.0.7 on 2024-09-11 21:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_subscription_confirmed_alter_subscription_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
